stages:
  # 建立flask專用的 Docker Image
  - name: Publish Flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: app/${CICD_GIT_REPO_NAME}-web:latest
        pushRemote: true
        registry: 10.50.1.63:5443
      env:
        PLUGIN_INSECURE: "true"

  # 部屬使用者應用(app)
  - name: Deploy app-web
    steps:
    - applyAppConfig:
        catalogTemplate: cattle-global-data:iii-dev-charts3-web
        version: 0.1.0
        name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web
        #targetNamespace: p-v2nzs-pipeline
        targetNamespace: ${CICD_GIT_REPO_NAME}
        answers:
          # 基礎pipeline參數
          git.url: ${CICD_GIT_URL}
          git.branch: ${CICD_GIT_BRANCH}
          git.commitID: ${CICD_GIT_COMMIT}
          git.repoName: ${CICD_GIT_REPO_NAME}
          # web參數設定
          web.type: uwsgi-flask
          # 10.50.1.63:5443/app/${CICD_GIT_REPO_NAME}-web
          web.image: 10.50.1.63:5443/app/${CICD_GIT_REPO_NAME}-web
          web.tag: latest
          checkmarx.enabled: false
          newman.enabled: false
          apieditor.enabled: true
  
  # (選擇性)部屬使用者的資料庫
  - name: Deploy db
    steps:
      - applyAppConfig:
          catalogTemplate: cattle-global-data:iii-dev-charts3-db
          version: 0.1.0
          name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db
          #targetNamespace: p-v2nzs-pipeline
          targetNamespace: ${CICD_GIT_REPO_NAME}
          answers:
            # 這裡是為了50與140環境測試
            git.host: "10.50.1.53"
            # 這裡是為了告訴要處理的git來源為何
            git.repoName: ${CICD_GIT_REPO_NAME}
            git.branch: ${CICD_GIT_BRANCH}
            db.type: mariadb
            db.gui: true
            # 使用者資料庫管理密碼
            db.username: bear
            db.password: bearisbear
            # 使用者初始想要建立的資料庫名稱
            db.name: health


  #- name: Deploy simple-no-db
  #  steps:
  #  - applyAppConfig:
  #      catalogTemplate: cattle-global-data:iii-dev-charts3-web-db
  #      version: 0.1.0
  #      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-simple-no-db
  #      targetNamespace: p-v2nzs-pipeline
  #      answers:
  #        web.name: uwsgi-flask
  #        web.image: 10.50.1.63:5443/${CICD_GIT_REPO_NAME}-web
          #git.url: ${CICD_GIT_URL}
          #git.repoName: ${CICD_GIT_REPO_NAME}
          #git.branch: ${CICD_GIT_BRANCH}
          #web.tag: latest
          #service.db.enable: "false"
          #service.db.gui: "false"
          #extraEnv[0].name: test
          #extraEnv[0].value: bearflask
          #extraEnv[1].name: test2
    
  #- name: Deploy app-with-mysql
  #  steps:
  #  - applyAppConfig:
  #      catalogTemplate: cattle-global-data:iii-dev-charts3-web-db
  #      version: 0.1.0
  #      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-app-with-mysql
  #      targetNamespace: p-v2nzs-pipeline
  #      answers:
  #        web.name: flask
  #        web.image: 10.50.1.63:5443/${CICD_GIT_REPO_NAME}-web
  #        db.image: 10.50.1.63:5443/${CICD_GIT_REPO_NAME}-db:latest
  #        service.db.enable: "true"
  #        service.db.type: mysql
  #        service.db.rootpassword: bearflaskmysqlmysql
  #        #git.url: ${CICD_GIT_URL}
  #        #git.repoName: ${CICD_GIT_REPO_NAME}
  #        #git.branch: ${CICD_GIT_BRANCH}
  #        #web.tag: latest
  #        #db.tag: latest
  #        #service.db.gui: "false"         

  #- name: Deploy app-with-postgresql
  #  steps:
  #  - applyAppConfig:
  #      catalogTemplate: cattle-global-data:iii-dev-charts3-web-db
  #      version: 0.1.0
  #      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-app-with-postgresql
  #      targetNamespace: p-v2nzs-pipeline
  #      answers:
  #        web.name: flask
  #        web.image: 127.0.0.1:34957/${CICD_GIT_REPO_NAME}-web
  #        db.image: 127.0.0.1:34957/${CICD_GIT_REPO_NAME}-db:latest
  #        service.db.enable: "true"
  #        service.db.type: postgresql
  #        service.db.rootpassword: bearflaskpostgresql
  #        #git.url: ${CICD_GIT_URL}
  #        #git.repoName: ${CICD_GIT_REPO_NAME}
  #        #git.branch: ${CICD_GIT_BRANCH}
  #        #web.tag: latest
  #        #db.tag: latest 
  #        #service.db.gui: false
          

  #- name: Deploy app-with-mysql-and-gui
  #  steps:
  #  - applyAppConfig:
  #      catalogTemplate: cattle-global-data:iii-dev-charts3-web-db
  #      version: 0.1.0
  #      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-app-with-mysql-and-gui
  #      targetNamespace: p-v2nzs-pipeline
  #      answers:
  #        web.name: flask
  #        web.image: 127.0.0.1:34957/${CICD_GIT_REPO_NAME}-web
  #        db.image: 127.0.0.1:34957/${CICD_GIT_REPO_NAME}-db:latest
  #        service.db.enable: true
  #        service.db.gui: true
  #        service.db.type: mysql
  #        service.db.rootpassword: bearflaskmysql
  #        #git.url: ${CICD_GIT_URL}
  #        #git.repoName: ${CICD_GIT_REPO_NAME}
  #        #git.branch: ${CICD_GIT_BRANCH}
  #        #web.tag: latest        
  #        #db.tag: latest

  #- name: Deploy app-with-mongodb-and-gui
  #  steps:
  #  - applyAppConfig:
  #      catalogTemplate: cattle-global-data:iii-dev-charts3-web-db
  #      version: 0.1.0
  #      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-app-with-mongodb-and-gui
  #      targetNamespace: p-v2nzs-pipeline
  #      answers:
  #        web.name: flask
  #        web.image: 127.0.0.1:34957/${CICD_GIT_REPO_NAME}-web
  #        db.image: 127.0.0.1:34957/${CICD_GIT_REPO_NAME}-db:latest
  #        service.db.enable: true
  #        service.db.gui: true
  #        service.db.type: mongodb
  #        service.db.rootpassword: bearflaskmysql
  #        #git.url: ${CICD_GIT_URL}
  #        #git.repoName: ${CICD_GIT_REPO_NAME}
  #        #git.branch: ${CICD_GIT_BRANCH}
  #        #web.tag: latest        
  #        #db.tag: latest
